# Usa uma versão fixa e estável do Miniconda
FROM continuumio/miniconda3:4.12.0

# Evita prompts durante a instalação
ENV DEBIAN_FRONTEND=noninteractive

# Instala o FastQC a partir dos canais oficiais
RUN conda install -c bioconda -c conda-forge fastqc=0.12.1 -y && \
    conda clean -afy

# Cria um diretório de trabalho
WORKDIR /data

# Define o executável padrão (ao rodar o container, executa o FastQC)
ENTRYPOINT ["fastqc"] 