# Usa uma versão fixa e estável do Miniconda
FROM continuumio/miniconda3

# Evita prompts durante a instalação
ENV DEBIAN_FRONTEND=noninteractive

# Instala o FastQC a partir dos canais oficiais
RUN conda install -c bioconda -c conda-forge multiqc -y && \
    conda clean -afy

# Cria um diretório de trabalho
WORKDIR /data_compiled

# Define o executável padrão (ao rodar o container, executa o Multiqc)
ENTRYPOINT ["multiqc"] 