# Usa uma versão fixa e estável do Miniconda
FROM continuumio/miniconda3

# Evita prompts durante a instalação
ENV DEBIAN_FRONTEND=noninteractive

# Instala o FastQC a partir dos canais oficiais
RUN conda install -c bioconda -c conda-forge megahit -y && \
    conda clean -afy

# Cria um diretório de trabalho
WORKDIR /data_assembly

# Define o executável padrão (ao rodar o container, executa o Megahit)
ENTRYPOINT ["megahit"] 